########################################
# KIPET version 1.0.6
# Date: 2021-09-23-19-35-37
# File: <ipython-input-14-0b8e7117258d>
# ReactionModel instance: rxn1
########################################

# Simulator: Initializing with starting values
# Simulator: Using the fe method
# Simulator: Setting up simulation model
Warning! Since Cm-matrix contains negative values Kipet is assuming a derivative of Cm has been inputted
Warning! Since Cm-matrix contains negative values Kipet is assuming a derivative of Cm has been inputted
Warning! Since Cm-matrix contains negative values Kipet is assuming a derivative of Cm has been inputted
# TemplateBuilder: Preparing model for simulator
# Simulator: Finished creating simulator
# Simulator: Completed successfully

# VarianceEstimator: All variances provided / concentration problem

# ParameterEstimator: Creating instance

# Warning: Template already populated
ReactionModel: Generating base model (self._model)
# TemplateBuilder: Preparing model for p_estimator
# TemplateBuilder: Preparing model for p_estimator
# ParameterEstimator: The variances being used are:
 {'A': 1, 'B': 1, 'C': 1}
# ParameterEstimator: Solving the parameter fitting problem...

ERROR: Solver (asl) returned non-zero return code (1)
ERROR: Solver log: [K_AUG] written by D.T. @2018

    : Unknown keyword "linear_solver" Unknown keyword "nlp_scaling_method"
    Unknown keyword "max_iter" Unknown keyword "linear_solver" Unknown keyword
    "nlp_scaling_method" Unknown keyword "max_iter"
Traceback (most recent call last):
  File "/home/paperspace/anaconda3/envs/ckipetenv/lib/python3.8/site-packages/kipet/main_modules/reaction_model.py", line 1773, in run_opt
    results = self._run_opt_core()
  File "/home/paperspace/anaconda3/envs/ckipetenv/lib/python3.8/site-packages/kipet/main_modules/reaction_model.py", line 1903, in _run_opt_core
    self._run_pe_opt()
  File "/home/paperspace/anaconda3/envs/ckipetenv/lib/python3.8/site-packages/kipet/main_modules/reaction_model.py", line 1687, in _run_pe_opt
    self._run_opt('p_estimator', **pe_settings)
  File "/home/paperspace/anaconda3/envs/ckipetenv/lib/python3.8/site-packages/kipet/main_modules/reaction_model.py", line 1942, in _run_opt
    self.results_dict[estimator] = getattr(self, estimator).run_opt(*args, **kwargs)
  File "/home/paperspace/anaconda3/envs/ckipetenv/lib/python3.8/site-packages/kipet/estimator_tools/parameter_estimator.py", line 181, in run_opt
    self.objective_value = self._solve_model(
  File "/home/paperspace/anaconda3/envs/ckipetenv/lib/python3.8/site-packages/kipet/estimator_tools/parameter_estimator.py", line 350, in _solve_model
    obj_val = self.optimize(model, sigma_sq)
  File "/home/paperspace/anaconda3/envs/ckipetenv/lib/python3.8/site-packages/kipet/estimator_tools/parameter_estimator.py", line 536, in optimize
    self._regular_optimization(model)
  File "/home/paperspace/anaconda3/envs/ckipetenv/lib/python3.8/site-packages/kipet/estimator_tools/parameter_estimator.py", line 523, in _regular_optimization
    solver_results = optimizer.solve(model, tee=False, symbolic_solver_labels=True)
  File "/home/paperspace/anaconda3/envs/ckipetenv/lib/python3.8/site-packages/Pyomo-5.7.3-py3.8-linux-x86_64.egg/pyomo/opt/base/solvers.py", line 601, in solve
    raise ApplicationError(
pyutilib.common._exceptions.ApplicationError: Solver (asl) did not exit normally
########################################
# KIPET version 1.0.6
# Date: 2021-09-23-19-35-37
# File: <ipython-input-14-0b8e7117258d>
# ReactionModel instance: rxn1
########################################

# Simulator: Initializing with starting values
# Simulator: Using the fe method
# Simulator: Setting up simulation model
# Warning: Template already populated
# TemplateBuilder: Preparing model for simulator
# Simulator: Finished creating simulator
# Simulator: Completed successfully

# VarianceEstimator: All variances provided / concentration problem

# ParameterEstimator: Creating instance

# Warning: Template already populated
# TemplateBuilder: Preparing model for p_estimator
# ParameterEstimator: The variances being used are:
 {'A': 1, 'B': 1, 'C': 1}
# ParameterEstimator: Solving the parameter fitting problem...

WARNING: Loading a SolverResults object with a warning status into
    model.name="unknown";
      - termination condition: other
      - message from solver: <undefined>
WARNING: The solution of the iteration was unsuccessful. The problem is solved with additional solver options.
WARNING: A file named '/home/paperspace/learn_kipet/kipet_paresto/ipopt.opt'
    exists in the current working directory, but Ipopt options file options
    (i.e., options that start with 'OF_') were provided. The options file
    '/home/paperspace/learn_kipet/kipet_paresto/ipopt.opt' will be ignored.
WARNING: Loading a SolverResults object with a warning status into
    model.name="unknown";
      - termination condition: other
      - message from solver: <undefined>
WARNING: The solution of the iteration was unsuccessful. The problem is solved with additional solver options.
WARNING: A file named '/home/paperspace/learn_kipet/kipet_paresto/ipopt.opt'
    exists in the current working directory, but Ipopt options file options
    (i.e., options that start with 'OF_') were provided. The options file
    '/home/paperspace/learn_kipet/kipet_paresto/ipopt.opt' will be ignored.
WARNING: Loading a SolverResults object with a warning status into
    model.name="unknown";
      - termination condition: other
      - message from solver: <undefined>
The current iteration was unsuccessful.

# Parameter Values
             k1 = 5.0000e+00
             k2 = 5.0000e+00
              A = 1.0000e+00
              B = 0.0000e+00
              C = 0.0000e+00
Traceback (most recent call last):
  File "/home/paperspace/anaconda3/envs/ckipetenv/lib/python3.8/site-packages/kipet/main_modules/reaction_model.py", line 1773, in run_opt
    results = self._run_opt_core()
  File "/home/paperspace/anaconda3/envs/ckipetenv/lib/python3.8/site-packages/kipet/main_modules/reaction_model.py", line 1903, in _run_opt_core
    self._run_pe_opt()
  File "/home/paperspace/anaconda3/envs/ckipetenv/lib/python3.8/site-packages/kipet/main_modules/reaction_model.py", line 1687, in _run_pe_opt
    self._run_opt('p_estimator', **pe_settings)
  File "/home/paperspace/anaconda3/envs/ckipetenv/lib/python3.8/site-packages/kipet/main_modules/reaction_model.py", line 1942, in _run_opt
    self.results_dict[estimator] = getattr(self, estimator).run_opt(*args, **kwargs)
  File "/home/paperspace/anaconda3/envs/ckipetenv/lib/python3.8/site-packages/kipet/estimator_tools/parameter_estimator.py", line 192, in run_opt
    return self._get_results()
  File "/home/paperspace/anaconda3/envs/ckipetenv/lib/python3.8/site-packages/kipet/estimator_tools/parameter_estimator.py", line 217, in _get_results
    raise Exception("The current iteration was unsuccessful.")
Exception: The current iteration was unsuccessful.
########################################
# KIPET version 1.0.6
# Date: 2021-09-23-19-35-37
# File: <ipython-input-14-0b8e7117258d>
# ReactionModel instance: rxn1
########################################

# Simulator: Initializing with starting values
# Simulator: Using the fe method
# Simulator: Setting up simulation model
# Warning: Template already populated
# TemplateBuilder: Preparing model for simulator
# Simulator: Finished creating simulator
# Simulator: Completed successfully

# VarianceEstimator: All variances provided / concentration problem

# ParameterEstimator: Creating instance

# Warning: Template already populated
# TemplateBuilder: Preparing model for p_estimator
# ParameterEstimator: The variances being used are:
 {'A': 1, 'B': 1, 'C': 1}
# ParameterEstimator: Solving the parameter fitting problem...

WARNING: Loading a SolverResults object with a warning status into
    model.name="unknown";
      - termination condition: other
      - message from solver: <undefined>
WARNING: The solution of the iteration was unsuccessful. The problem is solved with additional solver options.
WARNING: A file named '/home/paperspace/learn_kipet/kipet_paresto/ipopt.opt'
    exists in the current working directory, but Ipopt options file options
    (i.e., options that start with 'OF_') were provided. The options file
    '/home/paperspace/learn_kipet/kipet_paresto/ipopt.opt' will be ignored.
WARNING: Loading a SolverResults object with a warning status into
    model.name="unknown";
      - termination condition: other
      - message from solver: <undefined>
WARNING: The solution of the iteration was unsuccessful. The problem is solved with additional solver options.
WARNING: A file named '/home/paperspace/learn_kipet/kipet_paresto/ipopt.opt'
    exists in the current working directory, but Ipopt options file options
    (i.e., options that start with 'OF_') were provided. The options file
    '/home/paperspace/learn_kipet/kipet_paresto/ipopt.opt' will be ignored.
WARNING: Loading a SolverResults object with a warning status into
    model.name="unknown";
      - termination condition: other
      - message from solver: <undefined>
The current iteration was unsuccessful.

# Parameter Values
             k1 = 5.0000e+00
             k2 = 5.0000e+00
              A = 1.0000e+00
              B = 0.0000e+00
              C = 0.0000e+00
Traceback (most recent call last):
  File "/home/paperspace/anaconda3/envs/ckipetenv/lib/python3.8/site-packages/kipet/main_modules/reaction_model.py", line 1773, in run_opt
    results = self._run_opt_core()
  File "/home/paperspace/anaconda3/envs/ckipetenv/lib/python3.8/site-packages/kipet/main_modules/reaction_model.py", line 1903, in _run_opt_core
    self._run_pe_opt()
  File "/home/paperspace/anaconda3/envs/ckipetenv/lib/python3.8/site-packages/kipet/main_modules/reaction_model.py", line 1687, in _run_pe_opt
    self._run_opt('p_estimator', **pe_settings)
  File "/home/paperspace/anaconda3/envs/ckipetenv/lib/python3.8/site-packages/kipet/main_modules/reaction_model.py", line 1942, in _run_opt
    self.results_dict[estimator] = getattr(self, estimator).run_opt(*args, **kwargs)
  File "/home/paperspace/anaconda3/envs/ckipetenv/lib/python3.8/site-packages/kipet/estimator_tools/parameter_estimator.py", line 192, in run_opt
    return self._get_results()
  File "/home/paperspace/anaconda3/envs/ckipetenv/lib/python3.8/site-packages/kipet/estimator_tools/parameter_estimator.py", line 217, in _get_results
    raise Exception("The current iteration was unsuccessful.")
Exception: The current iteration was unsuccessful.
